# Generated by Django 6.0.2 on 2026-02-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
